# Generated by Django 5.2.5 on 2025-08-16 11:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="first_name",
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name="user",
            name="last_name",
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name="user",
            name="phone",
            field=models.CharField(
                error_messages={"unique": "A Phone number already exists."},
                max_length=18,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(
                help_text="Required 30 characters or fewer. Letters, digits, dots and underscore only.",
                max_length=30,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Only letters, numbers, dots and underscore are allowed.",
                        regex="^[\\w.]+$",
                    )
                ],
            ),
        ),
    ]
