# Generated by Django 5.2.5 on 2025-08-16 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_alter_user_first_name_alter_user_last_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="profile_header",
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
