# Generated by Django 5.2.5 on 2025-08-27 12:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_userprofile_profile_header"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="phone",
            field=models.CharField(
                error_messages={
                    "unique": "This phone number has already been registered."
                },
                max_length=18,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(
                help_text="Required 30 characters or fewer. Letters, digits, dots and underscore only.",
                max_length=30,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Only letters, numbers, dots and underscores are allowed.",
                        regex="^[\\w.]+$",
                    )
                ],
            ),
        ),
    ]
